CREATE TABLE Attivita (idAttivita bigint(20) NOT NULL AUTO_INCREMENT, name varchar(255), description varchar(255), maxParticipants int(10) NOT NULL, actualParticipants int(10) NOT NULL, `date` date, hour int(10), PRIMARY KEY (idAttivita));
CREATE TABLE Ombrellone (idOmbrellone bigint(20) NOT NULL AUTO_INCREMENT, price float NOT NULL, ombrelloneType varchar(255), PRIMARY KEY (idOmbrellone));
CREATE TABLE Piatto (idPiatto bigint(20) NOT NULL AUTO_INCREMENT, name varchar(255), description varchar(255), price float NOT NULL, piattoType varchar(255), PRIMARY KEY (idPiatto));
CREATE TABLE Lettino (idLettino bigint(20) NOT NULL AUTO_INCREMENT, price float NOT NULL, lettinoType varchar(255), PRIMARY KEY (idLettino));
CREATE TABLE Prenotazione (idPrenotazione bigint(20) NOT NULL AUTO_INCREMENT, startDate date, endDate date, prenotationType int(10), oggettoPrenotato bigint(20), Clienteid bigint(20) NOT NULL, PRIMARY KEY (idPrenotazione));
CREATE TABLE Ordine (idOrdine bigint(20) NOT NULL AUTO_INCREMENT, price float NOT NULL, orderedDishes int(10), startOrder date, endOrder date, Clienteid bigint(20) NOT NULL, PRIMARY KEY (idOrdine));
CREATE TABLE Promozione (idPromozione bigint(20) NOT NULL AUTO_INCREMENT, name varchar(255), description varchar(255), startDate date, endDate date, PRIMARY KEY (idPromozione));
CREATE TABLE Cliente (id bigint(20) NOT NULL AUTO_INCREMENT, name varchar(255), surname varchar(255), email varchar(255), guestType varchar(255), PRIMARY KEY (id));
CREATE TABLE GestoreChalet (id bigint(20) NOT NULL AUTO_INCREMENT, name varchar(255), surname varchar(255), email varchar(255), guestType varchar(255), PRIMARY KEY (id));
CREATE TABLE Prenotazione_Cliente (ClienteidCliente bigint(20) NOT NULL, PrenotazioneidPrenotazione bigint(20) NOT NULL, PRIMARY KEY (ClienteidCliente, PrenotazioneidPrenotazione));
CREATE TABLE Prenotazione_Attività (PrenotazioneidPrenotazione bigint(20) NOT NULL, AttivitaidAttivita bigint(20) NOT NULL, PRIMARY KEY (PrenotazioneidPrenotazione));
CREATE TABLE Prenotazione_Ombrellone (PrenotazioneidPrenotazione bigint(20) NOT NULL, OmbrelloneidOmbrellone bigint(20) NOT NULL, PRIMARY KEY (PrenotazioneidPrenotazione));
CREATE TABLE Prenotazione_Lettino (PrenotazioneidPrenotazione bigint(20) NOT NULL, LettinoidLettino bigint(20) NOT NULL, PRIMARY KEY (PrenotazioneidPrenotazione));
CREATE TABLE Cliente_Ordine (ClienteidCliente bigint(20) NOT NULL, OrdineidOrdine bigint(20) NOT NULL, PRIMARY KEY (ClienteidCliente, OrdineidOrdine));
CREATE TABLE Ordine_Piatto (OrdineidOrdine bigint(20) NOT NULL, Piattoid bigint(20) NOT NULL, quantity int(11), PRIMARY KEY (OrdineidOrdine, Piattoid));
CREATE TABLE UserHandler (id bigint(20) NOT NULL, token bigint(20) NOT NULL, PRIMARY KEY (id, token));
CREATE TABLE Piatto_Promozione (PiattoidPiatto bigint(20) NOT NULL, PromozioneidPromozione bigint(20) NOT NULL, PRIMARY KEY (PiattoidPiatto, PromozioneidPromozione));
ALTER TABLE Prenotazione_Cliente ADD CONSTRAINT FKPrenotazio967778 FOREIGN KEY (ClienteidCliente) REFERENCES Cliente (id);
ALTER TABLE Prenotazione_Ombrellone ADD CONSTRAINT FKPrenotazio335853 FOREIGN KEY (PrenotazioneidPrenotazione) REFERENCES Prenotazione (idPrenotazione);
ALTER TABLE Prenotazione_Ombrellone ADD CONSTRAINT FKPrenotazio342164 FOREIGN KEY (OmbrelloneidOmbrellone) REFERENCES Ombrellone (idOmbrellone);
ALTER TABLE Prenotazione_Attività ADD CONSTRAINT FKPrenotazio91332 FOREIGN KEY (PrenotazioneidPrenotazione) REFERENCES Prenotazione (idPrenotazione);
ALTER TABLE Prenotazione_Attività ADD CONSTRAINT FKPrenotazio392658 FOREIGN KEY (AttivitaidAttivita) REFERENCES Attivita (idAttivita);
ALTER TABLE Prenotazione_Lettino ADD CONSTRAINT FKPrenotazio374470 FOREIGN KEY (PrenotazioneidPrenotazione) REFERENCES Prenotazione (idPrenotazione);
ALTER TABLE Prenotazione_Lettino ADD CONSTRAINT FKPrenotazio196158 FOREIGN KEY (LettinoidLettino) REFERENCES Lettino (idLettino);
ALTER TABLE Cliente_Ordine ADD CONSTRAINT FKCliente_Or418035 FOREIGN KEY (ClienteidCliente) REFERENCES Cliente (id);
ALTER TABLE Cliente_Ordine ADD CONSTRAINT FKCliente_Or554114 FOREIGN KEY (OrdineidOrdine) REFERENCES Ordine (idOrdine);
ALTER TABLE Ordine_Piatto ADD CONSTRAINT FKOrdine_Pia783542 FOREIGN KEY (OrdineidOrdine) REFERENCES Ordine (idOrdine);
ALTER TABLE Ordine_Piatto ADD CONSTRAINT FKOrdine_Pia831526 FOREIGN KEY (Piattoid) REFERENCES Piatto (idPiatto);
ALTER TABLE Prenotazione_Cliente ADD CONSTRAINT FKPrenotazio168773 FOREIGN KEY (PrenotazioneidPrenotazione) REFERENCES Prenotazione (idPrenotazione);
ALTER TABLE Piatto_Promozione ADD CONSTRAINT FKPiatto_Pro267233 FOREIGN KEY (PiattoidPiatto) REFERENCES Piatto (idPiatto);
ALTER TABLE Piatto_Promozione ADD CONSTRAINT FKPiatto_Pro525584 FOREIGN KEY (PromozioneidPromozione) REFERENCES Promozione (idPromozione);
ALTER TABLE Prenotazione ADD CONSTRAINT FKPrenotazio895675 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
ALTER TABLE Ordine ADD CONSTRAINT FKOrdine229541 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
